### ISSUE TITLE
Sharing our CVPR'23 paper

### ISSUE THREAD

**Issue by linzhiqiu** [zhengli97/ATPrompt#1]
Hey,

I am Zhiqiu Lin, a final-year PhD student at Carnegie Mellon University working with Prof. Deva Ramanan. I come across your interesting work and would like to share some of our papers on fine-tuning of VLMs: 

[Multimodality Helps Unimodality: Cross-Modal Few-Shot Learning with Multimodal Models](https://arxiv.org/abs/2301.06267) (CVPR'23). 

Hope you find it relevant!

Best,
Zhiqiu

**Comment by zhengli97** [comment]
Thank you for sharing this interesting work.
