### ISSUE TITLE
ModuleNotFoundError: No module named 'templates'

### ISSUE THREAD

**Issue by wdi-nancy** [zhengli97/ATPrompt#3]
When running the scripts, I encountered this error. It seems that there are missing templates in Dassl.

`/Dassl.pytorch/dassl/data/data_manager.py", line 12, in <module>
    from templates.imagenet_templates import IMAGENET_TEMPLATES
ModuleNotFoundError: No module named 'templates'`

**Comment by zhengli97** [comment]
Thank you for your feedback. I have fixed this issue and updated the code. Please check the updated code to see if it runs successfully.
